---
- name: Get URL pointing to the latest alacritty .deb
  shell: wget --quiet https://github.com/jwilm/alacritty/releases -O- | grep "_amd64.deb" | grep release | cut -d '"' -f2 | head -1 | sed "s/^/https:\/\/github.com/"
  register: alacritty_latest_deb_url
  changed_when: false
  ignore_errors: yes  # Use ignore_errors instead of failed_when

- name: Fail the task if wget fails
  fail:
    msg: "Failed to retrieve the latest alacritty .deb URL"
  when: alacritty_latest_deb_url.rc != 0

- name: Install alacritty
  apt:
    deb: "{{ alacritty_latest_deb_url.stdout }}"
    state: present