---
- name: Add alacritty repository
  ansible.builtin.apt_repository:
    repo: "{{ alacritty_repo }}"
    state: present

- name: Install alacritty
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - alacritty