---
- name: Download nvim image
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /opt/nvim.appimage
    mode: 0755

- name: Run nvim.appimage briefly in the background
  command: /opt/nvim.appimage
  async: 5
  poll: 0

- name: Ensure nvim.appimage is not running
  command: pkill -f nvim.appimage