- name: Install prerequisites for fuck
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - python3-dev
      - python3-pip
      - python3-setuptools

- name: Install fuck with pip
  pip:
    name: thefuck
    executable: pip3
    extra_args: "--user"

- name: Add fuck path to PATH environment variablee
  ansible.builtin.lineinfile:
    path: /home/{{ user }}/.zshrc
    line: "export PATH=$PATH:/home/{{ user }}/.local/bin"
    insertafter: EOF