---
- name: Install xclip
  apt:
    name: xclip
    state: present
  become: true
  
- name: Add 'clipboard' alias to zsh config
  ansible.builtin.lineinfile:
    path: "{{ '/home/' + user + '/.zshrc' if user != 'root' else '/root/.zshrc' }}"
    line: alias clipboard='xclip -sel clip'
    insertafter: EOF