---
- name: Install zsh-autosuggestion
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ '/home/' + user + '/.oh-my-zsh/custom/plugins/zsh-autosuggestions' if user != 'root' else '/root/.oh-my-zsh/custom/plugins/zsh-autosuggestions' }}" 

- ansible.builtin.replace:
    path: "{{ '/home/' + user + '/.zshrc' if user != 'root' else '/root/.zshrc' }}"
    regexp: '^(plugins=\(.*)(\))$'
    replace: '\1 zsh-autosuggestions\2'