---
- name: Install required packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - "{{ item }}"
  with_items: "{{ required_packages }}"
  notify:
    - Install pyenv