- name: Add DNS entries to /etc/resolv.conf
  blockinfile:
    path: /etc/resolv.conf
    block: "{{ lookup('template', 'roles/prerequisites/templates/resolv.conf.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK "
    insertbefore: BOF
    backup: yes