---
- name: Install required Python stuffs
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - python3
      - python3-pip
      - virtualenv
  notify: 
    - Install pipenv

