- name: Uninstall older versions of docker
  ansible.builtin.apt:
    pkg:
      - {{ older_docker_packages }}
    state: absent

- name: Make directory for gpg key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download gpg key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Get architecture of host
  ansible.builtin.shell: "dpkg --print-architecture"
  register: architecture

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    update_cache: yes
    repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install docker packages
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - {{ docker_packages }}
    state: present

- name: Verify docker installation
  ansible.builtin.command: docker run hello-world
  register: result

- name: Docker installation status
  ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"
