- name: Check if Snap package manager is installed
  command: dpkg -s snapd
  register: snap_output
  ignore_errors: true

- name: Install Snap package manager
  apt:
    name: snapd
    state: present
  when: snap_output.rc != 0
