---
# vars file for tools
shadowsocks_version: "1.3.2"
older_docker_packages:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin